FROM ruby:3.1
RUN apt-get update -qq && apt-get install -y postgresql-client --no-install-recommends && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN gem install bundler
RUN bundle config --global frozen 1
RUN bundle config set --local without 'development test'
RUN bundle install
COPY . /app
ARG REDIS_HOST
ENV REDIS_HOST $REDIS_HOST
RUN bundle exec rails DATABASE_URL=postgresql:does_not_exist assets:precompile
