version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./db/dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  css:
    build: .
    command: bundle exec rails tailwindcss:watch
    volumes:
      - .:/app
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - dev.env
    stdin_open: true
    tty: true
  redis:
    image: redis:7
