---
version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.6-node
      - image: cimg/postgres:12.12
    environment:
      DATABASE_URL: postgres://postgres@localhost/circle_test
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: bundle exec rails db:setup --trace
      - run:
          name: Test
          command: bundle exec rspec
workflows:
  test:
    jobs:
      - test
